# TensorFlow 2 quickstart for beginners

In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.0.0'

In [6]:
mnist = tf.keras.datasets.mnist

In [7]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [8]:
x_train, x_test = x_train / 255.0, x_test / 255.0

In [9]:
x_train.shape

(60000, 28, 28)

In [10]:
x_test.shape

(10000, 28, 28)

## Build the model

In [11]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10),
])

In [12]:
predictions = model(x_train[:1]).numpy()
predictions


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.



array([[-0.17000191,  0.2541611 , -0.01202071,  0.16346963, -0.21317688,
         0.30034152, -0.09648857,  0.03800698, -0.03802229,  0.3106893 ]],
      dtype=float32)

In [13]:
tf.nn.softmax(predictions)

<tf.Tensor: id=109, shape=(1, 10), dtype=float32, numpy=
array([[0.07862049, 0.12015653, 0.09207593, 0.10973889, 0.07529828,
        0.12583554, 0.08461788, 0.09679944, 0.08971266, 0.12714441]],
      dtype=float32)>

In [15]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [16]:
loss_fn(y_train[:1], predictions).numpy()

2.0727797

In [17]:
model.compile(optimizer='adam', loss=loss_fn, metrics=['accuracy'])

In [18]:
model.fit(x_train, y_train, epochs=5)

Train on 60000 samples
Epoch 1/5
60000/60000 [==============================] - 6s 101us/sample - loss: 0.2966 - accuracy: 0.9140
Epoch 2/5
60000/60000 [==============================] - 6s 108us/sample - loss: 0.1415 - accuracy: 0.9576
Epoch 3/5
60000/60000 [==============================] - 6s 107us/sample - loss: 0.1047 - accuracy: 0.9679
Epoch 4/5
60000/60000 [==============================] - 7s 109us/sample - loss: 0.0863 - accuracy: 0.9735
Epoch 5/5
60000/60000 [==============================] - 6s 105us/sample - loss: 0.0745 - accuracy: 0.9765


In [19]:
model.evaluate(x_test, y_test, verbose=2)

10000/1 - 1s - loss: 0.0363 - accuracy: 0.9778


[0.07174210707428866, 0.9778]

## Wrap the model to get probabilities

In [20]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax(),
])

In [21]:
probability_model(x_test[:5])

<tf.Tensor: id=30015, shape=(5, 10), dtype=float32, numpy=
array([[4.8771760e-08, 1.5577297e-09, 2.0949077e-05, 2.0858680e-04,
        3.4727065e-12, 6.5311646e-08, 5.5122936e-14, 9.9976975e-01,
        2.5940841e-07, 3.3157522e-07],
       [2.0895895e-07, 3.4832719e-05, 9.9996114e-01, 1.1042570e-06,
        1.8246404e-14, 1.9983879e-06, 1.2294365e-07, 7.7026818e-14,
        6.0650461e-07, 1.3867802e-13],
       [2.3104154e-07, 9.9886763e-01, 4.3141795e-04, 9.3389745e-06,
        5.0040613e-05, 9.3655799e-06, 2.3724459e-05, 3.9050521e-04,
        2.1645383e-04, 1.2254180e-06],
       [9.9411583e-01, 4.9235787e-08, 2.2322682e-04, 4.5755796e-06,
        1.0702432e-06, 4.2752738e-04, 9.8138526e-06, 7.3677464e-04,
        1.9399766e-07, 4.4809571e-03],
       [5.6920990e-06, 1.8491060e-07, 5.1916966e-05, 3.3711754e-07,
        9.9774975e-01, 3.1093250e-06, 7.0629693e-07, 4.7912129e-04,
        3.1919308e-06, 1.7060037e-03]], dtype=float32)>